
export type PublishMetadata = {
  title: string;
  description: string;
  tags: string[];
  thumbnailPrompt?: string;
  target: "youtube" | "gumroad";
};

export function generatePublishMetadata(prompt: string, target: "youtube" | "gumroad"): PublishMetadata {
  const clean = prompt.trim() || "Untitled project";
  const title = clean.slice(0, 70);
  const description = `${clean}

Generated by FairlyOddOS Publish Metadata pass.
Call to action: watch, download, support, and share.`;
  const tags = clean
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 10);
  const thumbnailPrompt = `Create a compelling ${target} thumbnail for: ${clean}`;
  return { title, description, tags, thumbnailPrompt, target };
}
