import type { GenFile } from "./files";

export function localGenerate(type: string, brand = "FairlyOdd"): GenFile[] {
  if(type === "affiliate_site"){
    return [
      { path:"index.html", content:`<!doctype html><html><head><meta charset="utf-8"><title>${brand} Affiliate Site</title></head><body><h1>${brand} Affiliate Microsite</h1><p>Generated locally by OddEngine.</p></body></html>` },
      { path:"keywords/bitcoin-mining.html", content:"<h1>bitcoin-mining</h1><p>placeholder</p>" },
      { path:"keywords/best-trading-apps.html", content:"<h1>best-trading-apps</h1><p>placeholder</p>" },
      { path:"keywords/crypto-wallets.html", content:"<h1>crypto-wallets</h1><p>placeholder</p>" },
      { path:"assets/README.txt", content:"Put images/css here." },
      { path:"sitemap.xml", content:`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>/</loc></url></urlset>` },
    ];
  }
  if(type === "fairlyodd_dashboard"){
    return [
      { path:"README.md", content:"# FairlyOdd Dashboard\nGenerated by OddEngine.\n" },
      { path:"theme.css", content:":root{--bg:#0b0f14;--fg:#e7eef7;} body{background:var(--bg);color:var(--fg);} "},
      { path:"App.tsx", content:`import React from "react";\nexport default function App(){return <div style={{padding:16}}>FairlyOdd Dashboard</div>;}` },
    ];
  }
  if(type === "crypto_dashboard"){
    return [{ path:"README.md", content:"# Crypto / Mining Dashboard\nGenerated by OddEngine.\n" }];
  }
  if(type === "product_page"){
    return [{ path:"index.html", content:`<!doctype html><html><head><meta charset="utf-8"><title>${brand} Product</title></head><body><h1>${brand} Product Page</h1></body></html>` }];
  }
  if(type === "marketplace_scaffold"){
    return [
      { path:"README.md", content:"# Template Marketplace Scaffold\nGenerated by OddEngine.\n" },
      { path:"catalog.json", content: JSON.stringify({templates:[]}, null, 2) }
    ];
  }
  return [];
}


export type MoneyPackKind =
  | "trader_pack"
  | "mining_pack"
  | "affiliate_pack"
  | "full_bundle";

function prefixFiles(prefix: string, files: GenFile[]): GenFile[] {
  return files.map(f => ({ path: `${prefix}/${f.path}`.replace(/\/+/g, "/"), content: f.content }));
}

export function generateMoneyPack(kind: MoneyPackKind, brand = "FairlyOdd"): GenFile[] {
  const out: GenFile[] = [];
  if(kind === "trader_pack" || kind === "full_bundle"){
    out.push(...prefixFiles("trader/dashboard", localGenerate("fairlyodd_dashboard", brand)));
    out.push({ path:"trader/README.md", content:`# ${brand} Trader Pack\n\n- Dashboard starter\n- Add widgets + APIs\n`});
  }
  if(kind === "mining_pack" || kind === "full_bundle"){
    out.push(...prefixFiles("mining/dashboard", localGenerate("crypto_dashboard", brand)));
    out.push({ path:"mining/README.md", content:`# ${brand} Mining Pack\n\n- Mining dashboard starter\n- Add pools + hashrate + payouts\n`});
  }
  if(kind === "affiliate_pack" || kind === "full_bundle"){
    out.push(...prefixFiles("affiliate/site", localGenerate("affiliate_site", brand)));
    out.push({ path:"affiliate/README.md", content:`# ${brand} Affiliate Pack\n\n- Microsite starter\n- Add keywords/pages\n`});
  }
  out.push({ path:"README.md", content:`# ${brand} Money Pack\nGenerated by OddEngine.\n`});
  return out;
}
